### Importing I-D Arrays

In [1]:
#importing numpy library

import sys
import numpy as np

In [2]:
#creating a numpy array and assigning it to a
a=np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [5]:
#Multi Indexing an Array

a[[0,2,-1]]

array([1, 3, 4])

In [6]:
a[0],a[2],a[-1]

(1, 3, 4)

In [13]:
b=np.array([1,2,3,4],dtype=np.int8)

In [14]:
b.dtype

dtype('int8')

###  Dimensions and Shape

In [20]:
A=np.array([[1,2,3],
          [4,5,6]])

In [21]:
A.shape

(2, 3)

In [22]:
A.ndim

2

In [23]:
A.size

6

In [24]:
A.dtype

dtype('int32')

In [25]:
A.shape

(2, 3)

### Slicing the Matrix/array

In [27]:
A=np.array([[1,2,3],[4,5,6],[11,12,13]])

In [31]:
A[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13]])

In [32]:
A[1:3]

array([[ 4,  5,  6],
       [11, 12, 13]])

In [51]:
A[2:3]

array([], shape=(0, 3), dtype=int32)

In [35]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [36]:
#selecting 2nd row and 2nd column
A[2:,2:]

array([[13]])

In [39]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13]])

In [40]:
#Selecting all rows and columns except the 2nd column
A[:,:2]

array([[ 1,  2],
       [ 4,  5],
       [11, 12]])

In [41]:
#Selecting all rows and all column
A[:,:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13]])

In [49]:
#Selecting all rows and only 2nd column
A[:,2:]

array([[ 3],
       [ 6],
       [13]])

### Some Statistics

In [45]:
A.sum()

57

In [46]:
A.mean()

6.333333333333333

In [52]:
A.std()

4.268749491621899

In [53]:
A.var()

18.22222222222222

In [54]:
#Adding values w.r.t columns
A.sum(axis=0)

array([16, 19, 22])

In [55]:
#Adding values w.r.t rows
A.sum(axis=1)

array([ 6, 15, 36])

### Broadcasting and Vectorized operations

In [68]:
x=np.arange(4)

In [69]:
x

array([0, 1, 2, 3])

In [70]:
x=x*(x+10)

In [75]:
x

array([ 0, 11, 24, 39])

In [71]:
[i*10 for i in x]

[0, 110, 240, 390]

In [72]:
x+20

array([20, 31, 44, 59])

### Boolean arrays

In [73]:
x>x.mean()

array([False, False,  True,  True])

In [74]:
x>=2

array([False,  True,  True,  True])

In [77]:
x[x>=2]

array([11, 24, 39])

In [78]:
x[(x>=2) & (x>x.mean())]

array([24, 39])

### Linear Algebra

In [82]:
b=np.array([[6,7],[8,9],[10,11]])

In [83]:
#Dot product of a and b
a.dot(b)

array([[ 52,  58],
       [124, 139],
       [196, 220]])

In [85]:
#assigning dot product of a and b to c
c=a @ b

In [86]:
c.T

array([[ 52, 124, 196],
       [ 58, 139, 220]])